import express from 'express';
const r = express.Router();
import controllers_misc_controller from '../controllers/misc.controller.js';
const { circular } = controllers_misc_controller;
import middleware_auth_middleware from '../middleware/auth.middleware.js';
const { protect, adminOrTeacher } = middleware_auth_middleware;
r.get('/', protect, circular.getAll);
r.post('/', protect, adminOrTeacher, circular.create);
r.put('/:id', protect, adminOrTeacher, circular.update);
r.delete('/:id', protect, adminOrTeacher, circular.delete);
export default r;
