import express from 'express';
const r = express.Router();
import controllers_misc_controller from '../controllers/misc.controller.js';
const { expense } = controllers_misc_controller;
import middleware_auth_middleware from '../middleware/auth.middleware.js';
const { protect, adminOnly } = middleware_auth_middleware;
r.get('/summary', protect, expense.getSummary);
r.get('/', protect, expense.getAll);
r.post('/', protect, adminOnly, expense.create);
export default r;
