import express from 'express';
const r = express.Router();
import c from '../controllers/inventory.controller.js';
import middleware_auth_middleware from '../middleware/auth.middleware.js';
const { protect, adminOnly } = middleware_auth_middleware;
r.get('/stats', protect, c.getInventoryStats);
r.get('/transactions', protect, c.getTransactions);
r.post('/transactions', protect, c.addTransaction);
r.get('/', protect, c.getAllItems);
r.post('/', protect, adminOnly, c.createItem);
r.get('/:id', protect, c.getItem);
r.put('/:id', protect, adminOnly, c.updateItem);
export default r;
