import express from 'express';
const r = express.Router();
import controllers_misc_controller from '../controllers/misc.controller.js';
const { library } = controllers_misc_controller;
import middleware_auth_middleware from '../middleware/auth.middleware.js';
const { protect, libStaff } = middleware_auth_middleware;
r.get('/books', protect, library.getBooks);
r.post('/books', protect, libStaff, library.addBook);
r.get('/issues', protect, library.getIssues);
r.post('/issue', protect, libStaff, library.issueBook);
r.put('/return/:id', protect, libStaff, library.returnBook);
export default r;
