const express = require('express');
const r = express.Router();
const { library } = require('../controllers/misc.controller');
const { protect, libStaff } = require('../middleware/auth.middleware');
r.get('/books', protect, library.getBooks);
r.post('/books', protect, libStaff, library.addBook);
r.get('/issues', protect, library.getIssues);
r.post('/issue', protect, libStaff, library.issueBook);
r.put('/return/:id', protect, libStaff, library.returnBook);
module.exports = r;
