import express from 'express';
const r = express.Router();
import c from '../controllers/outpass.controller.js';
import middleware_auth_middleware from '../middleware/auth.middleware.js';
const { protect, hostelStaff } = middleware_auth_middleware;
r.post('/', protect, c.createOutpass);
r.get('/', protect, c.getOutpasses);
r.put('/:id/status', protect, hostelStaff, c.updateOutpassStatus);
r.put('/:id/return', protect, hostelStaff, c.markReturned);
export default r;
