import express from 'express';
const r = express.Router();
import c from '../controllers/outpass.controller.js';
import middleware_auth_middleware from '../middleware/auth.middleware.js';
const { protect, hostelOutpassStaff } = middleware_auth_middleware;
r.post('/', protect, c.createOutpass);
r.get('/', protect, c.getOutpasses);
r.put('/:id/status', protect, hostelOutpassStaff, c.updateOutpassStatus);
r.put('/:id/return', protect, hostelOutpassStaff, c.markReturned);
export default r;
