export {
  FiActivity,
  FiAlertCircle,
  FiAlertTriangle,
  FiAlertOctagon,
  FiArrowDown,
  FiArrowLeft,
  FiArrowRight,
  FiArrowUp,
  FiAward,
  FiBarChart2,
  FiBell,
  FiBook,
  FiBookOpen,
  FiCalendar,
  FiCamera,
  FiCheck,
  FiCheckCircle,
  FiChevronLeft,
  FiChevronRight,
  FiClipboard,
  FiClock,
  FiCoffee,
  FiCreditCard,
  FiEdit3,
  FiEye,
  FiFileText,
  FiHome,
  FiInfo,
  FiInbox,
  FiLogOut,
  FiLock,
  FiMenu,
  FiMinus,
  FiPackage,
  FiPhone,
  FiPlus,
  FiSearch,
  FiShield,
  FiShoppingBag,
  FiShoppingCart,
  FiTarget,
  FiTrendingDown,
  FiTrendingUp,
  FiUser,
  FiUserPlus,
  FiUsers,
  FiX,
} from 'react-icons/fi';

export { FaIndianRupeeSign as FiDollarSign } from 'react-icons/fa6';
export { HiOutlineHandRaised } from 'react-icons/hi2';
